env:
    browser: true
    es6: true
extends:
    - airbnb
    - plugin:prettier/recommended
parserOptions:
    ecmaVersion: 2020
    sourceType: module
rules:
    import/extensions: [error, ignorePackages]
    import/no-extraneous-dependencies: [error, { packageDir: '.' }]
